version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "[%(asctime)s] %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: log/main.log
    maxBytes: 268435456
    backupCount: 10
root:
  level: INFO
  handlers: [console, logfile]
